import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/Providers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <nav>
            <Link href='/'>Home</Link>
            <Link href='/cart'>Cart</Link>
            <Link href='/about'>About</Link>
          </nav>
          {children}
          </Providers>
      </body>
    </html>
  );
}
